require "pry"
require "nokogiri"
require "open-uri"
require "tty-prompt"
require "paint"
require_relative "./hollypop/version"


require_relative "./hollypop/cli"
require_relative "./hollypop/artist"
require_relative "./hollypop/question"
require_relative "./hollypop/game"
require_relative "./hollypop/scraper"
require_relative "./hollypop/movie"
require_relative "./hollypop/explore"
require_relative "./concerns/style"